name: Build Code Docs
on:
  push:
    branches:
      - main
      - test-me-*
  pull_request:
  workflow_dispatch:

jobs:
  # Checks for which PDFs need to be rebuilt
  changes:
    name: ğŸ§ Check What Changed
    runs-on: ubuntu-latest
    outputs:
      build_code_docs: ${{ steps.filter.outputs.continue }}
    steps:
      - name: ğŸ› Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: ğŸ§ Check What Changed
        id: filter
        run: scripts/what-code-changed ${{ github.ref_name == 'main' && '--main' || '' }} ${{ github.event_name == 'workflow_dispatch' && '--all' || '' }}

  build_code_docs:
    name: ğŸ— Build Code Docs
    runs-on: ubuntu-latest
    needs:
      - changes
    if: needs.changes.outputs.build_code_docs == 'true'
    steps:
      - name: ğŸ› Checkout
        uses: actions/checkout@v3

      - name: ğŸ’» Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16"

      - name: ğŸ’¿ Cache Node Modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: "${{ runner.os }}-build-${{ env.cache-name }}\
            -${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: ğŸš§ Install Dependencies
        run: npm ci

      - name: ğŸ‘· Build TypeDoc
        run: npx typedoc ./src

      - name: ğŸ’¾ Save HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: typedoc-report
          path: typedoc

  collect_results:
    name: ğŸ“‹ Collect Build Results
    needs:
      - changes
      - build_code_docs
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“‹ Check for Failures
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: echo job failed && exit 1
