name: Application Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - test/**
  push:
    branches:
      - main
    paths:
      - src/**
      - test/**

jobs:
  app_tests:
    name: ğŸ§ª Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ› Checkout
        uses: actions/checkout@v3

      - name: ğŸ’» Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "16"

      - name: ğŸ’¿ Cache Node Modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: "${{ runner.os }}-build-${{ env.cache-name }}\
            -${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: ğŸš§ Install Dependencies
        run: npm ci

      - name: ğŸ§ª Run Tests
        run: npx jest --group=unit --config=jest.unit.config.js

      - name: ğŸ’¾ Save Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-unit.json
          path: coverage-unit/coverage-final.json

  sys_tests:
    name: ğŸ§ª Integration Tests
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql://root:password@localhost:3306/sayyara
    steps:
      - name: ğŸ› Checkout
        uses: actions/checkout@v3

      - name: ğŸ’» Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "16"

      - name: ğŸ’¿ Cache Node Modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: "${{ runner.os }}-build-${{ env.cache-name }}\
            -${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: ğŸš§ Install Dependencies
        run: npm ci

      - name: ğŸ—„ï¸ Start MySQL Database
        run: docker compose up -d --wait

      - name: ğŸ“‹ Apply Prisma Schema
        run: npx prisma db push

      - name: ğŸ§ª Run Tests
        run: npx jest --runInBand --group=integration --config=jest.integration.config.js

      - name: ğŸ’¾ Save Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-integration.json
          path: coverage-integration/coverage-final.json

  coverage_report:
    name: ğŸ“Š Coverage Report
    runs-on: ubuntu-latest
    needs:
      - app_tests
      - sys_tests
    steps:
      - name: ğŸ› Checkout
        uses: actions/checkout@v3

      - name: ğŸ’» Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "16"

      - name: ğŸ’¿ Cache Node Modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: "${{ runner.os }}-build-${{ env.cache-name }}\
            -${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: ğŸš§ Install Dependencies
        run: npm ci

      - name: ğŸ“¥ Download Coverage Reports
        uses: actions/download-artifact@v3.0.1

      - name: ğŸš§ Move Reports To Correct Directory
        run: |
          mkdir coverage
          mv -v "coverage-unit.json/coverage-final.json" "coverage/coverage-unit.json"
          mv -v "coverage-integration.json/coverage-final.json" "coverage/coverage-integration.json"

      - name: ğŸš§ Build Coverage Report
        run: npx nyc report --temp-dir coverage --reporter cobertura

      - name: ğŸš§ Build Coverage Report Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          format: markdown
          output: both
          # fail_below_min: true
          thresholds: "60 80"

      - name: ğŸ“ Get Comment Body
        id: comment-body
        run: |
          ls -la
          body="$(cat code-coverage-results.md)"
          delimiter="$(openssl rand -hex 8)"
          echo "body<<$delimiter" >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT
        # cat code-coverage-results.md >> $GITHUB_OUTPUT

      - name: ğŸ“¤ Add Coverage Commit Comment
        uses: peter-evans/commit-comment@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          body: ${{ steps.comment-body.outputs.body }}

      - name: ğŸ“¤ Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2.3.1
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          message: ${{ steps.comment-body.outputs.body }}
