name: Application Tests
on:
  pull_request:
    branches:
      - main
    paths:
    - src/**
    - test/**
  push:
    branches:
      - main
    paths:
    - src/**
    - test/**

jobs:
  app_tests:
    name: ğŸ§ª Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ› Checkout
        uses: actions/checkout@v3

      - name: ğŸ’» Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '16'

      - name: ğŸ’¿ Cache Node Modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: "${{ runner.os }}-build-${{ env.cache-name }}\
            -${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: ğŸš§ Install Dependencies
        run: npm ci

      - name: ğŸ§ª Run Tests
        run: npx jest --group=unit --config=jest.unit.config.js

  sys_tests:
    name: ğŸ§ª Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ› Checkout
        uses: actions/checkout@v3

      - name: ğŸ’» Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "16"

      - name: ğŸ’¿ Cache Node Modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: "${{ runner.os }}-build-${{ env.cache-name }}\
            -${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: ğŸš§ Install Dependencies
        run: npm ci

      - name: ğŸ—„ï¸ Start MySQL Database
        run: docker compose up -d --wait

      - name: ğŸ“‹ Apply Prisma Schema
        run: npx prisma db push

      - name: ğŸ§ª Run Tests
        run: npx jest --runInBand --group=integration --config=jest.integration.config.js
